[tool.poetry]
name = "plugins"
version = "0.1.0"
description = ""
authors = ["Mathieu Tarral <mathieu.tarral@protonmail.com>"]
license = "private"
readme = "README.md"

[tool.poetry.scripts]
runner = 'plugins.__main__:runner'

[tool.poetry.dependencies]
python = "^3.11"
poethepoet = "^0.24.3"
ipdb = "^0.13.13"
click = "^8.1.7"
attrs = "^23.2.0"
neomodel = "^5.2.1"
dynaconf = "^3.2.5"
appdirs = "^1.4.4"


[tool.poetry.group.dev.dependencies]
black = "^24.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
